# Generated by Django 4.1.7 on 2023-07-25 06:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=500)),
                ("full_name", models.CharField(max_length=500)),
                ("mobile", models.CharField(max_length=500)),
                ("hno", models.CharField(max_length=500)),
                ("area_street", models.CharField(max_length=500)),
                ("alternate_mobile", models.CharField(max_length=500)),
                ("pincode", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=500)),
                ("is_home", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=500)),
                ("category_image", models.ImageField(upload_to="category_images/")),
            ],
        ),
        migrations.CreateModel(
            name="ChatWithus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("updated_time", models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Coupons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coupon_code", models.CharField(max_length=200)),
                ("coupon_description", models.TextField()),
                ("discount_percentage", models.IntegerField()),
                ("min_price_for_coupon_avail", models.IntegerField()),
                ("max_price", models.IntegerField()),
                ("no_of_days_valid", models.CharField(max_length=200)),
                ("no_of_coupons", models.IntegerField()),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("updated_time", models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomizableLogoTemplates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "template_image",
                    models.ImageField(blank=True, upload_to="template_images/"),
                ),
                ("max_characters", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CustomizedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=1000)),
                ("image", models.FileField(upload_to="user_customized_images")),
                ("size", models.CharField(max_length=1000)),
                ("quantity", models.IntegerField(default=1)),
                ("price", models.FloatField(default=0.0)),
                ("is_controler", models.BooleanField(default=True)),
                ("is_special_delivery", models.BooleanField(default=False)),
                ("special_delivery_charges", models.IntegerField(default=0)),
                ("description_by_user", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="CustomizerBackgroundimages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("background_name", models.CharField(max_length=400)),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, upload_to="customizer_background_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomizerColors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(max_length=250)),
                ("color_code", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="CustomizerDimensions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.FloatField(default=0.0)),
                ("length", models.FloatField(default=0.0)),
                ("price", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="CustomizerEmojis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.ImageField(blank=True, upload_to="customizer_emojis")),
                ("emoji_price", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="CustomizerFonts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("font_name", models.CharField(max_length=250)),
                (
                    "font_file",
                    models.FileField(blank=True, upload_to="customizer_fonts/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomizerShapes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shape_name", models.CharField(max_length=250)),
                (
                    "shape_image",
                    models.ImageField(blank=True, upload_to="customizer_shapes/"),
                ),
                ("shape_price", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Districts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district_name", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name_plural": "2.districts",
            },
        ),
        migrations.CreateModel(
            name="HighlightStories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("thumbnail", models.ImageField(upload_to="story_thumbnail/")),
                ("img_video", models.FileField(max_length=500, upload_to="stories/")),
                ("type", models.CharField(default="image", max_length=500)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("updated_time", models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_title", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
                ("sku_code", models.CharField(max_length=500, unique=True)),
                ("thumbnail", models.ImageField(upload_to="product_thumbnail/")),
                ("size_lable_1", models.CharField(max_length=500)),
                ("size_height_1", models.CharField(max_length=500)),
                ("size_width_1", models.CharField(max_length=500)),
                ("size_actual_price_1", models.FloatField()),
                ("size_selling_price_1", models.FloatField()),
                ("size_lable_2", models.CharField(default="", max_length=500)),
                ("size_height_2", models.CharField(default="", max_length=500)),
                ("size_width_2", models.CharField(default="", max_length=500)),
                ("size_actual_price_2", models.FloatField(default=0.0, null=True)),
                ("size_selling_price_2", models.FloatField(default=0.0, null=True)),
                ("size_lable_3", models.CharField(default="", max_length=500)),
                ("size_height_3", models.CharField(default="", max_length=500)),
                ("size_width_3", models.CharField(default="", max_length=500)),
                ("size_actual_price_3", models.FloatField(default=0.0, null=True)),
                ("size_selling_price_3", models.FloatField(default=0.0, null=True)),
                ("size_lable_4", models.CharField(default="", max_length=500)),
                ("size_height_4", models.CharField(default="", max_length=500)),
                ("size_width_4", models.CharField(default="", max_length=500)),
                ("size_actual_price_4", models.FloatField(default=0.0, null=True)),
                ("size_selling_price_4", models.FloatField(default=0.0, null=True)),
                ("size_lable_5", models.CharField(default="", max_length=500)),
                ("size_height_5", models.CharField(default="", max_length=500)),
                ("size_width_5", models.CharField(default="", max_length=500)),
                ("size_actual_price_5", models.FloatField(default=0.0, null=True)),
                ("size_selling_price_5", models.FloatField(default=0.0, null=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("stock_status", models.CharField(default="Available", max_length=500)),
                ("available_quantity", models.IntegerField(default=1)),
                ("no_of_wishlists", models.IntegerField(default=0)),
                ("no_of_cart", models.IntegerField(default=0)),
                ("no_of_returned", models.IntegerField(default=0)),
                ("no_of_orders", models.IntegerField(default=0)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("updated_time", models.TimeField(auto_now=True)),
                ("rating", models.FloatField(default=0)),
                ("numReviews", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.categories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="States",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_name", models.CharField(max_length=500)),
                (
                    "state_representing_image",
                    models.ImageField(null=True, upload_to="states/"),
                ),
            ],
            options={
                "verbose_name_plural": "1.States",
            },
        ),
        migrations.CreateModel(
            name="SuperAdminAcc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=500)),
                ("password", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.CharField(default="", max_length=500)),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.UUID("a11e2dee-ba45-4e67-8b5a-c1387575b24c"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("updated_time", models.TimeField(auto_now=True)),
                ("name", models.CharField(max_length=500)),
                ("email", models.EmailField(default="", max_length=500)),
                ("phone", models.CharField(max_length=100)),
                ("otp", models.CharField(default="00000", max_length=10)),
                (
                    "profile",
                    models.ImageField(null=True, upload_to="profile_pictures/"),
                ),
                ("device_id", models.CharField(max_length=500)),
                ("firebase_id", models.CharField(default="aaa", max_length=250)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_prime", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.IntegerField(default=1)),
                ("color", models.CharField(max_length=200)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_category", models.CharField(max_length=500)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.categories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("ratings", models.IntegerField()),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("updated_time", models.TimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to="maintribe.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductColorImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                ("color_name", models.CharField(max_length=500)),
                ("color_code", models.CharField(max_length=500)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_images",
                        to="maintribe.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_cat_product",
                to="maintribe.subcategories",
            ),
        ),
        migrations.CreateModel(
            name="PlaceOrderForLogoTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("email", models.CharField(max_length=500)),
                (
                    "template_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.customizablelogotemplates",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceOrderForCustomizedProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.IntegerField()),
                ("payment_method", models.CharField(max_length=200)),
                ("payment_done", models.BooleanField(default=False)),
                ("quantity", models.IntegerField(default=1)),
                ("order_status", models.CharField(default="1", max_length=200)),
                ("is_paid", models.BooleanField(default=False)),
                ("is_order_placed", models.BooleanField(default=True)),
                ("is_order_confirmed", models.BooleanField(default=False)),
                ("is_order_shipped", models.BooleanField(default=False)),
                ("is_order_on_the_way", models.BooleanField(default=False)),
                ("is_delivered", models.BooleanField(default=False)),
                ("order_placedAt", models.DateTimeField(auto_now=True)),
                ("order_confirmedAt", models.CharField(default="", max_length=200)),
                ("order_shippedAt", models.CharField(default="", max_length=200)),
                ("order_on_the_wayAt", models.CharField(default="", max_length=200)),
                ("order_deliveredAt", models.CharField(default="", max_length=200)),
                ("updatedAt", models.DateTimeField(auto_now_add=True)),
                ("transaction_id", models.CharField(blank=True, max_length=200)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.address",
                    ),
                ),
                (
                    "customized_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.customizedproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_coupon_applied", models.BooleanField(default=False)),
                ("total_amount", models.IntegerField()),
                ("payment_method", models.CharField(max_length=200)),
                ("payment_done", models.BooleanField(default=False)),
                ("quantity", models.IntegerField(default=1)),
                ("order_status", models.CharField(default="1", max_length=200)),
                ("is_paid", models.BooleanField(default=False)),
                ("is_order_placed", models.BooleanField(default=True)),
                ("is_order_confirmed", models.BooleanField(default=False)),
                ("is_order_shipped", models.BooleanField(default=False)),
                ("is_order_on_the_way", models.BooleanField(default=False)),
                ("is_delivered", models.BooleanField(default=False)),
                ("order_placedAt", models.DateTimeField(auto_now=True)),
                ("order_confirmedAt", models.CharField(default="", max_length=200)),
                ("order_shippedAt", models.CharField(default="", max_length=200)),
                ("order_on_the_wayAt", models.CharField(default="", max_length=200)),
                ("order_deliveredAt", models.CharField(default="", max_length=200)),
                ("updatedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.address",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="maintribe.coupons",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("size", models.IntegerField(default=1)),
                ("color", models.CharField(max_length=200)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="maintribe.ordermodel",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_coupon_applied", models.BooleanField(default=False)),
                ("total_amount", models.IntegerField()),
                ("payment_method", models.CharField(max_length=200)),
                ("payment_done", models.BooleanField(default=False)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "order_status",
                    models.CharField(default="order_placed", max_length=200),
                ),
                ("transaction_id", models.CharField(default="", max_length=250)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("updated_time", models.TimeField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.address",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="maintribe.coupons",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mandal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mandal_name", models.CharField(max_length=500)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.districts",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "3.Mandal",
            },
        ),
        migrations.AddField(
            model_name="districts",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="maintribe.states"
            ),
        ),
        migrations.AddField(
            model_name="customizedproduct",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="maintribe.customizercolors",
            ),
        ),
        migrations.AddField(
            model_name="customizedproduct",
            name="font",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="maintribe.customizerfonts",
            ),
        ),
        migrations.AddField(
            model_name="customizedproduct",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="maintribe.users"
            ),
        ),
        migrations.CreateModel(
            name="ChatWithUsReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reply_text", models.CharField(max_length=500)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("updated_time", models.TimeField(auto_now=True)),
                (
                    "userChat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.chatwithus",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chatwithus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="maintribe.users"
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("size", models.IntegerField(default=1)),
                ("color", models.CharField(max_length=200)),
                ("is_controller", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Banners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
                ("banner", models.ImageField(max_length=500, upload_to="banners/")),
                ("date", models.DateField(auto_now_add=True)),
                ("time", models.TimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.categories",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintribe.subcategories",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="maintribe.users"
            ),
        ),
    ]
