# Generated by Django 4.1.7 on 2023-05-23 05:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="order_confirmedAt",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_deliveredAt",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_on_the_wayAt",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_shippedAt",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("585d54c4-246a-45d5-8665-cb2c80707c3a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
