# Generated by Django 4.1.7 on 2023-05-23 05:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0002_alter_ordermodel_order_confirmedat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="order_confirmedAt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_deliveredAt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_on_the_wayAt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_shippedAt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("4c505ae2-123d-4f19-96e5-2be98d2c778b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
