# Generated by Django 4.1.7 on 2023-05-23 06:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0005_alter_users_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="numReviews",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("e825c88d-3bc9-4c89-b3eb-0e4bebb86c80"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
