# Generated by Django 4.1.7 on 2023-05-23 06:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0006_product_numreviews_alter_users_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("b2892bbe-559d-4767-9451-08595d482fcc"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
