# Generated by Django 4.1.7 on 2023-05-23 06:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0008_alter_users_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("cc5296fe-1e85-4738-be3d-3ae1afcbbab2"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
