# Generated by Django 4.1.7 on 2023-05-23 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0009_alter_product_rating_alter_users_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("f9be4d58-e792-4746-ad82-dc3cd154d461"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
