# Generated by Django 4.1.7 on 2023-05-23 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0010_alter_users_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("cb2993cd-9e10-4a74-973a-4259fdbdeb32"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
