# Generated by Django 4.1.7 on 2023-05-23 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0011_alter_users_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("e1df2f4b-934a-4a1d-9a8c-bb4aeaff01a6"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
