# Generated by Django 4.1.7 on 2023-05-23 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0013_alter_users_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_1_field",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_2_field",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_3_field",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_4_field",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_5_field",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("a07fe681-8f18-451a-8f43-d29def549f2b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
