# Generated by Django 4.1.7 on 2023-05-23 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0015_remove_product_discount_1_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("ffd638d8-47e4-49a9-a5c8-b79f2f743bd6"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
