# Generated by Django 4.1.7 on 2023-05-23 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0016_alter_users_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_2",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("30df2c08-0573-4a04-8798-47c6d7e61afd"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
