# Generated by Django 4.1.7 on 2023-05-23 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0018_remove_product_discount_2_alter_users_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("6401c9fc-70e6-49db-ba2a-78ccd00acb3b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
