# Generated by Django 4.1.7 on 2023-05-23 06:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0019_alter_users_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("ca1f3996-f44b-475a-8b68-40df260ae8db"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
