# Generated by Django 4.1.7 on 2023-05-23 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0020_alter_users_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("8e48c1b3-1c87-4cd2-a844-e6f74c07281b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
