# Generated by Django 4.1.7 on 2023-05-24 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0023_alter_users_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="order_confirmedAt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_deliveredAt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_on_the_wayAt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_shippedAt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("db552309-163e-4595-b761-74ef2a56ebb1"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
