# Generated by Django 4.1.7 on 2023-05-24 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0025_alter_ordermodel_order_confirmedat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("7ae1c7a9-cffb-4a06-b7bf-7be78c7802fa"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
