# Generated by Django 4.1.7 on 2023-05-24 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0026_alter_users_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("cb6195c5-4f96-4913-8ad8-713e8a7a7d60"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
