# Generated by Django 4.1.7 on 2023-05-24 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("maintribe", "0027_alter_users_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="order_confirmedAt",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_deliveredAt",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_on_the_wayAt",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_shippedAt",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("30bfa539-2e50-44f3-b8c2-6044af4cb3bc"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
